"""Initial migration.

Revision ID: 063128f6d29d
Revises: 
Create Date: 2024-11-12 00:55:18.700983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '063128f6d29d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_owner',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('hotelowner', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('hotelowner')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('bill_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('bill_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('bill_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hotel_owner', ['owner_id'], ['owner_id'])
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['order_id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hotel_owner', ['owner_id'], ['owner_id'])

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('offer_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hotel_owner', ['owner_id'], ['owner_id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('order_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('order_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'hotel_owner', ['owner_id'], ['owner_id'])
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('payment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['bill_id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('review_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('review_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('review_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'])
        batch_op.create_foreign_key(None, 'hotel_owner', ['owner_id'], ['owner_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_ibfk_2', 'item', ['item_id'], ['item_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('review_ibfk_1', 'hotelowner', ['owner_id'], ['owner_id'], ondelete='CASCADE')
        batch_op.alter_column('review_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_2', 'user', ['user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('payment_ibfk_1', 'bill', ['bill_id'], ['bill_id'], ondelete='SET NULL')
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_2', 'item', ['item_id'], ['item_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('order_ibfk_3', 'user', ['user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('order_ibfk_1', 'hotelowner', ['owner_id'], ['owner_id'], ondelete='CASCADE')
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('offer_ibfk_1', 'hotelowner', ['owner_id'], ['owner_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('item_ibfk_1', 'hotelowner', ['owner_id'], ['owner_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_ibfk_1', 'hotelowner', ['owner_id'], ['owner_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('bill_ibfk_2', 'order', ['order_id'], ['order_id'], ondelete='SET NULL')
        batch_op.alter_column('bill_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('hotelowner',
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hotelowner', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.drop_table('hotel_owner')
    # ### end Alembic commands ###
